### ISSUE TITLE
Issues with KSP 1.9.x and procedural parts 2.0.6

### ISSUE THREAD

**Issue by Lafreakshow** [HebaruSan/SmartTank#3]
I realize this mod isn't marked as compatible for either KSP 1.9 nor PP 2..0.6 but I thought I'd try it anyway and I ran into some issues right away. Bascially the mod does slightly less than nothing.

1) Diameter Matching seems to alter the values but fail to update the part so it actually resizes. I suspect this because when I attach a tank that is too small in diameter and enable fit to attached part nothing happens (well, FAR seems to notice that some part has changed and recalculates the area, something has to happen in the background), But at soon as I change the height of the tank, the diameter also updates. The samehappens when I change the diameter. A set to 0.1m and attached to 1.25m parts will instantly snap to 1.25m when I increase the diameter by the smalles amount. 

2) Fitting the tank type to an attached engine seems to not work at all, doesn't even trigger FAR like a change in size does, no log activity at all.

3) Fitting to TWR has the mod go crazy. Well, clikcing fit to TWR produces a single exception. Enabling auto fit to TWR produces the same exception once a frame:

```
 MissingMethodException: void ProceduralParts.ProceduralAbstractShape.Update() 
        SmartTank.SmartTankPart.Update () (at <fcffb6f688654296850abdb7feba9643>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
```

This is why I suspect the mod fails to update the change for some reason. I skimmed through the code and it seems to me that is exactly what this method would do. I don't know enough about C# or KSP modding to debug the issue though.

Some other things I notices in the process: SmartTanks aparently doesn't support the procedural SRB. I don't know if this is on purpose or if it was simply added after this mod was written. 

SmartTanks also still attaches itself to the procedural cone fuel tank, which was deprecated.

Now, I don't exactly know if this is an issue with just SmartTanks and PP or if some external factor plays into it. I have a metric ton of mods installed so a conflict may be possible too, Logs don't indicate anything like that though. I've also had issues with the Procedural Decoupler and Procedural Cone not having proper dimensions. Their diameter and heihgt (respectively) are waaaay too low. The decoupler, for example, has it's normal height of 0.2m but the size only goes up to 0.2m as well, the cone is even worse, it's height is limited to 0.001m. According to the tech nodes I've unlocked both of them should have much higher limits. Nothing in the log here either. Perhaps these issues are connected.

As stated, I don't know much about the gritty details of KSP modding but I will gladly help debugging this as much as I can. If there are any specific tests you want me to do or need any specific information, just tell me and I'll get on it.

One thing I will definetely try later on of (honestly just too tired right now) is set up a clean 1.9 install and see if the issue persists with one PP and SmartTanks.

**Comment by HebaruSan** [comment]
Yeah, the PP maintainers contacted me about some big changes they were working on that would break SmartTank a while back. I guess those changes have been released and SmartTank needs a rewrite. I'm not hugely motivated to work on this right now but I'll try to keep it in mind.

**Comment by HebaruSan** [comment]
Link to the PM thread that will presumably only work for me, for reference:

- https://forum.kerbalspaceprogram.com/index.php?/messenger/140742/

And the Discord message:

- https://discordapp.com/channels/206181796164009984/422839886337409042/724260342368305264

**Comment by Lafreakshow** [comment]
I see. I suspected something like this when I saw that the nose cone tank is still part of this mod. Anyway, Take your time. I don't want to make you pressure, resulting in you losing the motivation for modding entirely. We lost too many great modders to this already. Perhaps you should update the forum thread with a notice and the latest compatible PP version, to avoid more people coming at you like I did.

**Comment by HebaruSan** [comment]
Heh, I don't think this mod has enough users to be annoying even if they were all here shouting in my face in person. :grin:

**Comment by Lafreakshow** [comment]
I did some more test runs, mostly to debug the PP issue and I thought I'd better add the relevant bits I dicovered here:

The issues I have with certain Procedural Parts (...) parts are unrelated to SmartTanks. Seems to be an issue with 2.0.6 related to the tech tree limiting feature (as it works fine in Sandbox mode) and introduced while fixing another issue. Which means going back to 2.0.5 makes this disappear but then the game randomly crashes when right clicking anything PP related. For the interested, [I raised this issue over in the PP repo](https://github.com/KSP-RO/ProceduralParts/issues/267).

**Comment by DRVeyl** [comment]
Thankyou for bringing this up.  You might revert to 2.0.3 and check which parts are still an issue -- in particular as it relates to SmartParts compatibility.  I think that @HebaruSan graciously made most of the required changes when ProcParts 2.0 came out, but the call to the Update() method looks like the previous technique that did not update (pun intended).

2.0.4 re-introduced some of the minimum volume handling to support the RP-1 team, that was dropped from 2.0.  (Probably should have been 2.1: semver, I have failed you.)  2.0.5 and 2.0.6 attempted to fix some bugs that came with this.  I'm apparently still not there.

**Comment by HebaruSan** [comment]
> I think that @HebaruSan graciously made most of the required changes when ProcParts 2.0 came out,

Sort of; I worked on some of the changes but didn't release them, so the current SmartTank release will crash however it crashes.

**Comment by HebaruSan** [comment]
I have a rewrite just about ready for release, but I need KSP-RO/ProceduralParts#277 merged to make it work properly. I'm planning to wait till after PP releases those changes to make a new version of SmartTank.

**Comment by HebaruSan** [comment]
Fixed in latest release:

- https://github.com/HebaruSan/SmartTank/releases/tag/v0.5.0
