### ISSUE TITLE
no stock decouplers are available

### ISSUE THREAD

**Issue by linuxgurugamer** [HebaruSan/SmartTank#4]
Stock 1.12.2 game, only mods installed are  ProceduralParts, SmartTank & ModuleManager

When SmartTank is installed, no stock decouplers are available.

Logs:

[SmartTanksLog.zip](https://github.com/HebaruSan/SmartTank/files/7116561/SmartTanksLog.zip)

**Comment by HebaruSan** [comment]
This is a feature, not a bug. There's a checkbox that controls it. Closing because LGG doesn't respond to GitHub notifications, will communicate somewhere else.
